global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'proctoria-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'proctoria-analytics'
    static_configs:
      - targets: ['analytics:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'proctoria-websocket'
    static_configs:
      - targets: ['websocket:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'proctoria-plagiarism'
    static_configs:
      - targets: ['plagiarism:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s